name: Test minimum versions

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: test-min-versions-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test-min-torch:
    runs-on: ubuntu-latest
    name: Test minimum torch version
    steps:
      - uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install tests dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: run torch tests
        run: tox -e torch-tests-min-version
        env:
          # Use the CPU only version of torch when building/running the code
          PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu

  test-min-jax:
    runs-on: ubuntu-latest
    name: Test minimum jax version
    steps:
      - uses: actions/checkout@v3

      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install tests dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox

      - name: run jax tests
        run: tox -e jax-tests-min-version
